version: '3.7'
services:
  cyberchef:
    image: mpepping/cyberchef:latest
    container_name: cyberchef
    hostname: cyberchef
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../Config/nginx.conf:/etc/nginx/nginx.conf
      - ../Data/nginx:/etc/ssl/private

