version: '3.7'
services:
  cyberchef:
    image: mpepping/cyberchef:latest
    container_name: cyberchef
    hostname: cyberchef
    restart: unless-stopped
    labels:
      # Traefik Labels
      - "traefik.enable=true"
      # HTTPS Labels
      - "traefik.http.routers.cyberchef.rule=Host(`localhost`)" # Domain Name
      - "traefik.http.routers.cyberchef.entrypoints=web-secure"
      - "traefik.http.routers.cyberchef.middlewares=default-headers@file"
      - "traefik.http.routers.cyberchef.service=cyberchef"
      - "traefik.http.routers.cyberchef.tls=true"
      - "traefik.http.services.cyberchef.loadbalancer.server.port=8000" # Proxied Port
